stages:
  - build_image
  - build
  - test

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay

build-docker-image:
  image: 0xacab.org:4567/leap/docker/debian:bullseye_amd64
  stage: build_image
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "${CI_REGISTRY} | ${CI_REGISTRY_IMAGE} | ${IMAGE_TAG} | ${CI_COMMIT_REF_SLUG}"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  when: manual

# Basic android and gradle stuff
# Check linting
lintDebug:
  image : "registry.0xacab.org/leap/tor/tor-vpn:main"
  interruptible: true
  stage: test
  when: always
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

# Make Project
assembleDebug:
  image : "registry.0xacab.org/leap/tor/tor-vpn:main"
  interruptible: true
  stage: build
  script:
    - ./gradlew clean assembleDebug --stacktrace
  when: always
  artifacts:
    paths:
      - app/build/outputs/
      - build.log

# Run all tests, if any fails, interrupt the pipeline(fail it)
debugTests:
  image : "registry.0xacab.org/leap/tor/tor-vpn:main"
  interruptible: true
  stage: test
  when: always
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
